# Generated by Django 5.2.1 on 2026-07-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.employee'),
        ),
    ]
